_target_: peft.LoraConfig
r: 128
lora_alpha: 128
lora_dropout: 0.0
bias: none
init_lora_weights: true
target_modules:
  - self_attn.q
  - self_attn.k
  - self_attn.v
  - self_attn.o
  - cross_attn.q
  - cross_attn.k
  - cross_attn.v
  - cross_attn.o
  - ffn.0
  - ffn.2
